### PR TITLE
merge dev-loongarch branch into dev branch

### PR DESCRIPTION
**Pull request by enkerewpo**
finished boot zone0 root linux (`v6.9.8` with custom dtb and buildroot, linux kernel code not modified) on board Loongson TIMCREATE 3A5000+7A2000 mATX

linux: https://github.com/enkerewpo/linux-6.9.8-la64
buildroot: https://github.com/enkerewpo/buildroot-loongarch64

loongarch64 `hvisor-tool` porting WIP: https://github.com/enkerewpo/hvisor-tool

### CODE REVIEW

**Comment by enkerewpo** [comment]
new hvisor dev branch changes some inteface function like pagetable and platform config, I need some time to port the new changes to loongarch64

**Comment by enkerewpo** [comment]
I will reopen the pull request after testing new changes from `dev` branch

**Comment by enkerewpo** [comment]
The adaption to new zone config pagetable init has been done for loongarch64, now the hvisor non-arch code is up-to-date with `dev` branch. The `dev-loongarch64` branch now is capable of booting root linux 6.9.8 and using bash shell with no problem

**Review by KouweiLee — APPROVED** [review]

**Review by KouweiLee — CHANGES_REQUESTED** [review]
Since the latest version of ARM hvisor is available on dev-nxp, we have just merged dev-nxp into dev to test the correctness of ARM. Could you please test whether the current LoongArch can compile and run normally? If it works, we can proceed with the merge.

**Comment by enkerewpo** [comment]
the new changes on `dev`'s zone has been adapted to `dev-loongarch64`

**Review by KouweiLee — APPROVED** [review]

**Pull request merged**
